precompile(Tuple{Base.JuliaSyntax.var"#invoke_fixedworld#120"{Base.JuliaSyntax.var"#invoke_fixedworld#117#121"{typeof(Base.JuliaSyntax.core_parser_hook), UInt64}}, Core.SimpleVector, Vararg{Any}})
precompile(Tuple{Base.JuliaSyntax.var"#invoke_fixedworld#117#121"{typeof(Base.JuliaSyntax.core_parser_hook), UInt64}, Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}, Base.JuliaSyntax.var"#invoke_fixedworld#120"{Base.JuliaSyntax.var"#invoke_fixedworld#117#121"{typeof(Base.JuliaSyntax.core_parser_hook), UInt64}}, Core.SimpleVector, Vararg{Any}})
precompile(Tuple{typeof(Base.JuliaSyntax.core_parser_hook), Core.SimpleVector, String, Int64, Int64, Symbol})
precompile(Tuple{typeof(Base.unsafe_wrap), Type{Array{T, N} where N where T}, Ptr{UInt8}, Int64})
precompile(Tuple{typeof(Base.uv_writecb_task), Ptr{Nothing}, Int32})
precompile(Tuple{typeof(Base.println), Base.TTY, String})
precompile(Tuple{typeof(Core.memoryref), GenericMemory{:not_atomic, Base.Channel{Tuple{FASTX.FASTQ.Record, FASTX.FASTQ.Record}}, Core.AddrSpace{Core}(0x00)}})
precompile(Tuple{typeof(Base.Iterators.map), Function, Tuple{DataType, DataType}})
precompile(Tuple{Type{Base.Generator{I, F} where F where I}, typeof(Base.eltype), Tuple{DataType, DataType}})
precompile(Tuple{typeof(Base.getproperty), Base.Generator{Tuple{DataType, DataType}, typeof(Base.eltype)}, Symbol})
precompile(Tuple{typeof(Core.kwcall), NamedTuple{(:k, :check_rc), Tuple{Int64, Bool}}, typeof(Kmer64.filter_paired_reads_threaded), Vararg{String, 5}})
precompile(Tuple{Kmer64.var"#25#29"{String, String, Base.Channel{Base.Channel{Tuple{FASTX.FASTQ.Record, FASTX.FASTQ.Record}}}}})
precompile(Tuple{Kmer64.var"#28#32"{Array{Tuple{FASTX.FASTQ.Record, FASTX.FASTQ.Record}, 1}, Base.Channel{Tuple{FASTX.FASTQ.Record, FASTX.FASTQ.Record}}, Int64, Kmer64.KmerDataSet}})
precompile(Tuple{typeof(Base.getproperty), Task, Symbol})
precompile(Tuple{FASTX.FASTQ.var"#8#10", FASTX.FASTQ.Writer{TranscodingStreams.TranscodingStream{TranscodingStreams.Noop, Base.IOStream}}})